[package]
name = "qtranslate"
version = "0.1.0"
description = "A fast translation utility"
authors = ["quangdang46"]
edition = "2021"

[package.metadata]
tauri = { icon = "icons/icon.ico" }

[lib]
name = "qtranslate_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.1.4", features = [] }
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
enigo = { version = "0.2" }
arboard = "3"
urlencoding = "2"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
